# Pulse System Monitor Configuration

[window]
width = 800.0
height = 600.0
x = 100.0
y = 100.0
opacity = 0.95
transparent = false
always_on_top = false

[features]
show_cpu = true
show_memory = true
show_disk = true
show_network = true
show_processes = true

# Path to theme file
theme_path = "~/.config/pulse/themes/default.toml"

# Update interval in milliseconds
update_interval_ms = 1000
