vim.keymap.set("n", "<leader>ee", vim.cmd.Ex, { desc = "File Explorer" })
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move to Window Below" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move to Window Above" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move to Window Left" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move to Window Right" })
vim.keymap.set("t", "<esc>", [[<C-\><C-n>:q<CR>]], { desc = "Close Terminal" })
vim.keymap.set("n", "<c-k>", ":wincmd k<CR>")
vim.keymap.set("n", "<c-j>", ":wincmd j<CR>")
vim.keymap.set("n", "<c-h>", ":wincmd h<CR>")
vim.keymap.set("n", "<c-l>", ":wincmd l<CR>")
vim.keymap.set("n", "<leader>db", ":bd<CR>", { desc = "Delete Buffer" })
