-- This file is auto-generated by pywal.
-- For best results, use pywal with the `-s` flag to avoid terminal escape sequences.
-- Template by Gemini - MODIFIED FOR ZSH SYNTAX HIGHLIGHTING

return { {
    -- The default text color.
    foreground = '{foreground}',

    -- The default background color.
    background = '{background}',

    -- The color of the cursor.
    cursor_bg = '{cursor}',
    cursor_fg = '{background}',
    cursor_border = '{cursor}',

    -- The color of selected text.
    selection_fg = '{background}',
    selection_bg = '{color5}',

    -- The color of the scrollbar "thumb".
    scrollbar_thumb = '{color8}',

    -- The color of the split lines between panes.
    split = '{color8}',

    -- BRIGHTS: These are less likely to cause issues with zsh-syntax-highlighting.
    brights = { {
        '{color8}',
        '{color9}',
        '{color10}',
        '{color11}',
        '{color12}',
        '{color13}',
        '{color14}',
        '{color15}',
    } },

    -- Tab Bar Styling
    tab_bar = { {
        background = '{background}',
        active_tab = { {
            bg_color = '{color2}',
            fg_color = '{background}',
        } },
        inactive_tab = { {
            bg_color = '{color8}',
            fg_color = '{foreground}',
        } },
        inactive_tab_hover = { {
            bg_color = '{color7}',
            fg_color = '{background}',
        } },
        new_tab = { {
            bg_color = '{background}',
            fg_color = '{foreground}',
        } },
        new_tab_hover = { {
            bg_color = '{color3}',
            fg_color = '{background}',
        } },
    } },
} }
