-- This file is auto-generated by pywal.
-- For best results, use pywal with the `-s` flag to avoid terminal escape sequences.
-- Template by Gemini

return {
    -- The default text color.
    foreground = '{foreground}',

    -- The default background color.
    background = '{background}',

    -- The color of the cursor.
    cursor_bg = '{cursor}',
    cursor_fg = '{background}',
    cursor_border = '{cursor}',

    -- The color of selected text.
    selection_fg = '{background}',
    selection_bg = '{color5}',

    -- The color of the scrollbar "thumb".
    scrollbar_thumb = '{color8}',

    -- The color of the split lines between panes.
    split = '{color8}',

    -- The 16 ANSI colors.
    ansi = {{
        '{color0}',
        '{color1}',
        '{color2}',
        '{color3}',
        '{color4}',
        '{color5}',
        '{color6}',
        '{color7}',
    }},
    brights = {{
        '{color8}',
        '{color9}',
        '{color10}',
        '{color11}',
        '{color12}',
        '{color13}',
        '{color14}',
        '{color15}',
    }},

    -- (Optional) You can add specific color overrides for things like search matches.
    -- indexed = {{ [255] = "{foreground}" }},
    -- quick_select_label_bg = {{ Color = '{color2}' }},
    -- quick_select_label_fg = {{ Color = '{background}' }},
    -- quick_select_match_bg = {{ AnsiColor = 'Blue' }},

    -- Tab Bar Styling
    tab_bar = {{
        background = '{background}',

        -- Style for the active tab.
        active_tab = {{
            bg_color = '{color2}',
            fg_color = '{background}',
            -- You can add intensity and underline styles here.
            -- intensity = 'Bold',
            -- underline = 'Single',
        }},

        -- Style for inactive tabs.
        inactive_tab = {{
            bg_color = '{color8}',
            fg_color = '{foreground}',
        }},

        -- Style for inactive tabs when the mouse is hovering over them.
        inactive_tab_hover = {{
            bg_color = '{color7}',
            fg_color = '{background}',
        }},

        -- Style for the "new tab" button.
        new_tab = {{
            bg_color = '{background}',
            fg_color = '{foreground}',
        }},
        new_tab_hover = {{
            bg_color = '{color3}',
            fg_color = '{background}',
        }},
    }},
}}
