-- This file is auto-generated by pywal.
-- For best results, use pywal with the `-s` flag to avoid terminal escape sequences.
-- Template by Gemini - MODIFIED FOR ZSH SYNTAX HIGHLIGHTING

return {
    -- The default text color.
    foreground = '{foreground}',

    -- The default background color.
    background = '{background}',

    -- The color of the cursor.
    cursor_bg = '{cursor}',
    cursor_fg = '{background}',
    cursor_border = '{cursor}',

    -- The color of selected text.
    selection_fg = '{background}',
    selection_bg = '{color5}',

    -- The color of the scrollbar "thumb".
    scrollbar_thumb = '{color8}',

    -- The color of the split lines between panes.
    split = '{color8}',

    -- ANSI COLORS:
    -- We are INTENTIONALLY OMITTING the `ansi` table that defines the first 8 colors.
    -- This allows Wezterm to use its default, high-contrast ANSI colors, which
    -- prevents conflicts with tools like zsh-syntax-highlighting that rely on them.
    -- Pywal will still theme the rest of the terminal for a consistent look.

    -- BRIGHTS: These are less likely to cause issues, but you can comment out
    -- this section as well if you still see problems.
    brights = {{
        '{color8}',
        '{color9}',
        '{color10}',
        '{color11}',
        '{color12}',
        '{color13}',
        '{color14}',
        '{color15}',
    }},

    -- Tab Bar Styling
    tab_bar = {{
        background = '{background}',

        -- Style for the active tab.
        active_tab = {{
            bg_color = '{color2}',
            fg_color = '{background}',
        }},

        -- Style for inactive tabs.
        inactive_tab = {{
            bg_color = '{color8}',
            fg_color = '{foreground}',
        }},

        -- Style for inactive tabs when the mouse is hovering over them.
        inactive_tab_hover = {{
            bg_color = '{color7}',
            fg_color = '{background}',
        }},

        -- Style for the "new tab" button.
        new_tab = {{
            bg_color = '{background}',
            fg_color = '{foreground}',
        }},
        new_tab_hover = {{
            bg_color = '{color3}',
            fg_color = '{background}',
        }},
    }},
}}
