vim.pack.add({
    "https://github.com/nyoom-engineering/oxocarbon.nvim",
    "https://github.com/oskarnurm/koda.nvim",
    "https://github.com/folke/tokyonight.nvim",
    "https://github.com/rebelot/kanagawa.nvim",
    "https://github.com/ellisonleao/gruvbox.nvim",
    "https://github.com/sainnhe/sonokai",
    "https://github.com/ydkulks/cursor-dark.nvim",
    "https://github.com/olimorris/onedarkpro.nvim",
})
