#!/usr/bin/env bash

# Ask for a project to open with fzf or take in a path as a project
if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/Code ~/.config/ ~/Scripts/ -mindepth 1 -maxdepth 2 -type d | fzf)
fi

# Check to see if anything was selected
if [[ -z $selected ]]; then
	exit 0
fi

# Get the name of the project
project_name=${selected##*/}
project_name=${project_name//./_}

# Check if we're already in WezTerm
if [[ -n "$WEZTERM_PANE" ]]; then
  # We're in WezTerm, check if a tab with this project already exists
  existing_tab=$(wezterm cli list --format json | jq -r '.[] | select(.cwd == "'"$selected"'") | .tab_id' | head -1)

  if [[ -n "$existing_tab" ]]; then
    # Switch to existing tab
    wezterm cli activate-tab --tab-id "$existing_tab"
    echo "Switched to existing tab for '$project_name'."
  else
    # Create new tab
    wezterm cli spawn --cwd "$selected"
    echo "Created new tab for '$project_name'."
  fi
else
  # Not in WezTerm, start a new instance
  wezterm start --cwd "$selected" &
  echo "Started WezTerm in '$selected'."
fi
