---@class dark.Highlight: vim.api.keyset.highlight
---@field style? vim.api.keyset.highlight

---@alias dark.Highlights table<string, dark.Highlight>
--- Values must be a dark.Highlight table.
--- To link to another highlight group, use the `link` property:
--- e.g., { link = "Normal" }

---@alias dark.HighlightsFn fun(colors: dark.Palette, opts: dark.Config): dark.Highlights
--- Takes color palette and config, returns highlight definitions

---@class dark.Cache
--- Cached colorscheme data stored in stdpath("cache")
---@field groups dark.Highlights Compiled highlight groups
---@field config table The configuration fingerprint used to generate cache (for invalidation)

---@class dark.Palette
--- Color palette with semantic color names
---@field bg string?
---@field fg string?
---@field dim string?
---@field line string?
---@field keyword string?
---@field type string?
---@field operator string?
---@field comment string?
---@field border string?
---@field emphasis string?
---@field func string?
---@field string string?
---@field char string?
---@field special string?
---@field const string?
---@field highlight string?
---@field info string?
---@field success string?
---@field warning string?
---@field danger string?
---@field green string?
---@field orange string?
---@field red string?
---@field pink string?
---@field cyan string?

---@class dark.Config
--- User configuration options for the theme
---@field transparent? boolean
---@field theme? table<"dark"|"light", string>
---@field cache? boolean
---@field styles? table<string, vim.api.keyset.highlight>
---@field colors? table<string, string>
---@field auto? boolean
---@field on_highlights? fun(highlights: dark.Highlights, colors: dark.Palette)
