# Hardware Configuration Template
# This file should be replaced with your actual hardware-configuration.nix
# generated by nixos-generate-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # =========================================================================
  # Boot Configuration
  # =========================================================================
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Change to "kvm-amd" for AMD CPUs
  boot.extraModulePackages = [ ];

  # =========================================================================
  # Filesystems
  # =========================================================================
  # IMPORTANT: Replace these with your actual filesystem configuration
  # You can get this by running: nixos-generate-config

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-UUID";
    fsType = "vfat";
  };

  # If you have a swap partition, uncomment and configure:
  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/REPLACE-WITH-YOUR-UUID"; }
  # ];

  # =========================================================================
  # Hardware Support
  # =========================================================================

  # Intel CPU Microcode
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD, use:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # =========================================================================
  # Graphics - Intel GPU (from your Arch setup)
  # =========================================================================
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver  # LIBVA_DRIVER_NAME=iHD
      vaapiIntel          # LIBVA_DRIVER_NAME=i965 (older but works better for some)
      vaapiVdpau
      libvdpau-va-gl
      intel-compute-runtime # OpenCL
    ];
  };

  # For NVIDIA GPUs, uncomment:
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = false;
  #   open = false;
  #   nvidiaSettings = true;
  #   package = config.boot.kernelPackages.nvidiaPackages.stable;
  # };

  # For AMD GPUs, uncomment:
  # services.xserver.videoDrivers = [ "amdgpu" ];
  # hardware.opengl.extraPackages = with pkgs; [
  #   rocm-opencl-icd
  #   rocm-opencl-runtime
  # ];

  # =========================================================================
  # Networking Hardware
  # =========================================================================
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  # =========================================================================
  # Power Management
  # =========================================================================
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # =========================================================================
  # System Architecture
  # =========================================================================
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
