#!/bin/bash
# This script runs after pywal generates themes to handle app-specific tasks.

set -euo pipefail

# --- Zed Theme ---
ZED_THEMES_DIR="$HOME/.config/zed/themes"
SOURCE_THEME="$HOME/.cache/wal/pywal-zed-vesper.json"
DEST_THEME="$ZED_THEMES_DIR/pywal-theme.json"

# Ensure the destination directory exists
mkdir -p "$ZED_THEMES_DIR"

# Copy the file if the source exists
if [ -f "$SOURCE_THEME" ]; then
    cp "$SOURCE_THEME" "$DEST_THEME"
    echo "✅ Copied pywal theme to Zed themes directory."
fi

# --- Tmux Colors ---
# Generate tmux colors from pywal
echo "› Generating tmux colors..."
source "$HOME/.cache/wal/colors.sh"

cat > "$HOME/.cache/wal/colors-tmux.conf" << EOF
# Tmux colors from pywal
# Generated by post-pywal.sh

# Status bar colors
set -g status-style bg='$color0',fg='$foreground'
set -g status-left-style fg='$color1'
set -g status-right-style fg='$color2'

# Window status colors
set -g window-status-style fg='$color8',dim
set -g window-status-current-style fg='$foreground',bold,bg='$color1'
set -g window-status-bell-style fg='$color9',bold
set -g window-status-activity-style fg='$color3',bold

# Pane colors
set -g pane-border-style fg='$color8'
set -g pane-active-border-style fg='$color1',bright

# Message colors
set -g message-style fg='$foreground',bg='$color0'
set -g message-command-style fg='$foreground',bg='$color0'

# Mode colors (copy mode, etc.)
set -g mode-style fg='$background',bg='$color1'
EOF

echo "✅ Generated tmux colors file."

# Reload tmux if it's running
if command -v tmux &> /dev/null && tmux list-sessions &> /dev/null; then
    tmux source-file ~/.config/tmux/tmux.conf
    echo "✅ Reloaded tmux configuration."
fi

# --- Neovim Theme Reload ---
# Find all running Neovim instances and tell them to reload the theme.
# We suppress errors in case no instances are running.
echo "› Sending reload command to Neovim instances..."
for socket in $(find ${XDG_RUNTIME_DIR:-/tmp} -name "nvim*.sock" 2>/dev/null); do
    nvim --server "$socket" --remote-expr "vim.cmd('ReloadPywal')" &
done

# You can add other post-wal tasks here in the future
